import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>La Haus Coding challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <div className="h-screen flex items-center justify-center flex-col">
          <h1 className="text-4xl text-green-500 text-center my-6">
            La Haus Coding challenge
          </h1>
          <p className="text-2xl text-center text-gray-800 mb-3">
            This is a sample application for the La Haus coding challenge.
          </p>
        </div>
      </div>
    </>
  )
}

export default Home
